# RSpec.configure do |config|
#
#   config.before(:each, :feed) do
#
#     # Default User Feed Response
#     allow(Feed).to receive(:user_feed).and_return(
#
#          [{"actor"=>"53",
#            "foreign_id"=>"54",
#            "id"=>"0cbf7380-65f3-11e5-8080-80006cf73f47",
#            "message"=>"User 53 commented on 'Slot title 21'",
#            "object"=>"19",
#            "origin"=>nil,
#            "slot"=>
#                {"commentsCounter"=>1,
#                 "createdAt"=>"2015-09-28T15:10:26.843Z",
#                 "creator"=>
#                     {"createdAt"=>"2015-09-28T15:10:26.684Z",
#                      "deletedAt"=>nil,
#                      "id"=>56,
#                      "image"=>{"localId"=>nil, "publicId"=>nil},
#                      "updatedAt"=>"2015-09-28T15:10:26.684Z",
#                      "username"=>"User 52"},
#                 "deletedAt"=>nil,
#                 "endDate"=>"2019-10-22T21:44:02.000Z",
#                 "id"=>19,
#                 "likes"=>0,
#                 "location"=>nil,
#                 "media"=>
#                     [{"createdAt"=>"2015-09-28T15:10:26.916Z",
#                       "duration"=>nil,
#                       "localId"=>nil,
#                       "mediaId"=>12,
#                       "mediaType"=>"audio",
#                       "position"=>5,
#                       "publicId"=>"dfhjghjkdisudgfds7iy10",
#                       "title"=>"Title 9"},
#                      {"createdAt"=>"2015-09-28T15:10:26.904Z",
#                       "duration"=>nil,
#                       "localId"=>nil,
#                       "mediaId"=>11,
#                       "mediaType"=>"video",
#                       "position"=>4,
#                       "publicId"=>"dfhjghjkdisudgfds7iy9",
#                       "thumbnail"=>nil},
#                      {"createdAt"=>"2015-09-28T15:10:26.893Z",
#                       "duration"=>nil,
#                       "localId"=>nil,
#                       "mediaId"=>10,
#                       "mediaType"=>"video",
#                       "position"=>3,
#                       "publicId"=>"dfhjghjkdisudgfds7iy8",
#                       "thumbnail"=>nil},
#                      {"createdAt"=>"2015-09-28T15:10:26.881Z",
#                       "localId"=>nil,
#                       "mediaId"=>9,
#                       "mediaType"=>"image",
#                       "position"=>2,
#                       "publicId"=>"dfhjghjkdisudgfds7iy7"},
#                      {"createdAt"=>"2015-09-28T15:10:26.868Z",
#                       "localId"=>nil,
#                       "mediaId"=>8,
#                       "mediaType"=>"image",
#                       "position"=>1,
#                       "publicId"=>"dfhjghjkdisudgfds7iy6"},
#                      {"createdAt"=>"2015-09-28T15:10:26.856Z",
#                       "localId"=>nil,
#                       "mediaId"=>7,
#                       "mediaType"=>"image",
#                       "position"=>0,
#                       "publicId"=>"dfhjghjkdisudgfds7iy5"}],
#                 "notes"=>[],
#                 "reslotsCounter"=>0,
#                 "settings"=>{"alerts"=>"0000000000"},
#                 "shareUrl"=>nil,
#                 "startDate"=>"2019-09-22T21:44:02.000Z",
#                 "title"=>"Slot title 21",
#                 "updatedAt"=>"2015-09-28T15:10:26.843Z",
#                 "visibility"=>"public"},
#            "target"=>nil,
#            "time"=>"2015-09-28T15:10:27.000000",
#            "to"=>["aggregated:54", "notification:54"],
#            "user"=>
#                {"createdAt"=>"2015-09-25T21:22:16.257Z",
#                 "deletedAt"=>nil,
#                 "friendsCount"=>0,
#                 "id"=>53,
#                 "image"=>{"localId"=>nil, "publicId"=>nil},
#                 "reslotCount"=>0,
#                 "slotCount"=>5,
#                 "updatedAt"=>"2015-09-25T21:22:16.257Z",
#                 "username"=>"User 53"},
#            "verb"=>"comment"},
#
#           # 2nd activity to test pagination
#
#           {"actor"=>"53",
#            "foreign_id"=>"54",
#            "id"=>"aeaa8480-6622-11e5-8080-80001044bbff",
#            "message"=>"User 53 likes your slot",
#            "object"=>"19",
#            "origin"=>nil,
#            "slot"=>
#                {"commentsCounter"=>353,
#                 "createdAt"=>"2015-08-30T19:40:39.342Z",
#                 "creator"=>
#                     {"createdAt"=>"2015-08-30T19:40:36.540Z",
#                      "deletedAt"=>nil,
#                      "id"=>56,
#                      "image"=>{"localId"=>nil, "publicId"=>nil},
#                      "updatedAt"=>"2015-08-30T19:40:36.540Z",
#                      "username"=>"User 52"},
#                 "deletedAt"=>nil,
#                 "endDate"=>"2019-10-20T16:44:02.000Z",
#                 "id"=>19,
#                 "likes"=>1,
#                 "location"=>nil,
#                 "media"=>[],
#                 "notes"=>[],
#                 "reslotsCounter"=>0,
#                 "settings"=>{"alerts"=>"0000000000"},
#                 "shareUrl"=>nil,
#                 "startDate"=>"2019-09-20T16:44:02.000Z",
#                 "title"=>"National Creative Planner Jr.",
#                 "updatedAt"=>"2015-08-30T19:40:39.342Z",
#                 "visibility"=>"public"},
#            "target"=>nil,
#            "time"=>"2015-09-28T20:51:25.000000",
#            "to"=>["aggregated:54", "notification:54"],
#            "user"=>
#                {"createdAt"=>"2015-09-25T21:22:16.257Z",
#                 "deletedAt"=>nil,
#                 "friendsCount"=>0,
#                 "id"=>53,
#                 "image"=>{"localId"=>nil, "publicId"=>nil},
#                 "reslotCount"=>0,
#                 "slotCount"=>5,
#                 "updatedAt"=>"2015-09-25T21:22:16.257Z",
#                 "username"=>"User 53"},
#            "verb"=>"like"}]
#     )
#
#     # Users Aggregation Feed Response
#     allow(Feed).to receive(:news_feed).and_return(
#
#          [{"activities"=>
#                [{"actor"=>"53",
#                  "foreign_id"=>"61",
#                  "id"=>"0d580a00-65f3-11e5-8080-80002a923973",
#                  "message"=>"User 53 commented on 'Slot title 22'",
#                  "object"=>"20",
#                  "origin"=>nil,
#                  "slot"=>
#                      {"commentsCounter"=>1,
#                       "createdAt"=>"2015-09-28T15:10:28.819Z",
#                       "creator"=>
#                           {"createdAt"=>"2015-09-28T15:10:28.768Z",
#                            "deletedAt"=>nil,
#                            "id"=>60,
#                            "image"=>{"localId"=>nil, "publicId"=>nil},
#                            "updatedAt"=>"2015-09-28T15:10:28.768Z",
#                            "username"=>"User 54"},
#                       "deletedAt"=>nil,
#                       "endDate"=>"2019-10-23T22:44:02.000Z",
#                       "id"=>20,
#                       "likes"=>0,
#                       "location"=>nil,
#                       "media"=>
#                           [{"createdAt"=>"2015-09-28T15:10:28.889Z",
#                             "duration"=>nil,
#                             "localId"=>nil,
#                             "mediaId"=>18,
#                             "mediaType"=>"audio",
#                             "position"=>5,
#                             "publicId"=>"dfhjghjkdisudgfds7iy16",
#                             "title"=>"Title 15"},
#                            {"createdAt"=>"2015-09-28T15:10:28.877Z",
#                             "duration"=>nil,
#                             "localId"=>nil,
#                             "mediaId"=>17,
#                             "mediaType"=>"video",
#                             "position"=>4,
#                             "publicId"=>"dfhjghjkdisudgfds7iy15",
#                             "thumbnail"=>nil},
#                            {"createdAt"=>"2015-09-28T15:10:28.865Z",
#                             "duration"=>nil,
#                             "localId"=>nil,
#                             "mediaId"=>16,
#                             "mediaType"=>"video",
#                             "position"=>3,
#                             "publicId"=>"dfhjghjkdisudgfds7iy14",
#                             "thumbnail"=>nil},
#                            {"createdAt"=>"2015-09-28T15:10:28.854Z",
#                             "localId"=>nil,
#                             "mediaId"=>15,
#                             "mediaType"=>"image",
#                             "position"=>2,
#                             "publicId"=>"dfhjghjkdisudgfds7iy13"},
#                            {"createdAt"=>"2015-09-28T15:10:28.843Z",
#                             "localId"=>nil,
#                             "mediaId"=>14,
#                             "mediaType"=>"image",
#                             "position"=>1,
#                             "publicId"=>"dfhjghjkdisudgfds7iy12"},
#                            {"createdAt"=>"2015-09-28T15:10:28.831Z",
#                             "localId"=>nil,
#                             "mediaId"=>13,
#                             "mediaType"=>"image",
#                             "position"=>0,
#                             "publicId"=>"dfhjghjkdisudgfds7iy11"}],
#                       "notes"=>[],
#                       "reslotsCounter"=>0,
#                       "settings"=>{"alerts"=>"0000000000"},
#                       "shareUrl"=>nil,
#                       "startDate"=>"2019-09-23T22:44:02.000Z",
#                       "title"=>"Slot title 22",
#                       "updatedAt"=>"2015-09-28T15:10:28.819Z",
#                       "visibility"=>"public"},
#                  "target"=>nil,
#                  "time"=>"2015-09-28T15:10:28.000000",
#                  "to"=>["aggregated:61", "notification:61"],
#                  "user"=>
#                      {"createdAt"=>"2015-09-25T21:22:16.257Z",
#                       "deletedAt"=>nil,
#                       "friendsCount"=>0,
#                       "id"=>53,
#                       "image"=>{"localId"=>nil, "publicId"=>nil},
#                       "reslotCount"=>0,
#                       "slotCount"=>5,
#                       "updatedAt"=>"2015-09-25T21:22:16.257Z",
#                       "username"=>"User 53"},
#                  "verb"=>"comment"}],
#            "activity_count"=>6,
#            "actor_count"=>1,
#            "created_at"=>"2015-09-28T14:15:23.000000",
#            "group"=>"11357_2015-09-28",
#            "id"=>"0d580a00-65f3-11e5-92cb-0a1f1f7e985d",
#            "updated_at"=>"2015-09-28T15:10:28.000000",
#            "verb"=>"comment"}]
#      )
#
#     # Users Notification Feed Response
#     allow(Feed).to receive(:notification_feed).and_return(
#
#          [{"activities"=>
#                [{"actor"=>"53",
#                  "foreign_id"=>"65",
#                  "id"=>"27451d00-65f2-11e5-8080-800044759cad",
#                  "message"=>"User 53 commented on 'Slot title 23'",
#                  "object"=>"21",
#                  "origin"=>nil,
#                  "slot"=>
#                      {"commentsCounter"=>1,
#                       "createdAt"=>"2015-09-28T15:04:02.051Z",
#                       "creator"=>
#                           {"createdAt"=>"2015-09-28T15:04:02.035Z",
#                            "deletedAt"=>nil,
#                            "id"=>64,
#                            "image"=>{"localId"=>nil, "publicId"=>nil},
#                            "updatedAt"=>"2015-09-28T15:04:02.035Z",
#                            "username"=>"User 56"},
#                       "deletedAt"=>nil,
#                       "endDate"=>"2019-10-24T23:44:02.000Z",
#                       "id"=>21,
#                       "likes"=>0,
#                       "location"=>nil,
#                       "media"=>
#                           [{"createdAt"=>"2015-09-28T15:04:02.075Z",
#                             "duration"=>nil,
#                             "localId"=>nil,
#                             "mediaId"=>24,
#                             "mediaType"=>"audio",
#                             "position"=>5,
#                             "publicId"=>"dfhjghjkdisudgfds7iy22",
#                             "title"=>"Title 21"},
#                            {"createdAt"=>"2015-09-28T15:04:02.071Z",
#                             "duration"=>nil,
#                             "localId"=>nil,
#                             "mediaId"=>23,
#                             "mediaType"=>"video",
#                             "position"=>4,
#                             "publicId"=>"dfhjghjkdisudgfds7iy21",
#                             "thumbnail"=>nil},
#                            {"createdAt"=>"2015-09-28T15:04:02.067Z",
#                             "duration"=>nil,
#                             "localId"=>nil,
#                             "mediaId"=>22,
#                             "mediaType"=>"video",
#                             "position"=>3,
#                             "publicId"=>"dfhjghjkdisudgfds7iy20",
#                             "thumbnail"=>nil},
#                            {"createdAt"=>"2015-09-28T15:04:02.063Z",
#                             "localId"=>nil,
#                             "mediaId"=>21,
#                             "mediaType"=>"image",
#                             "position"=>2,
#                             "publicId"=>"dfhjghjkdisudgfds7iy19"},
#                            {"createdAt"=>"2015-09-28T15:04:02.060Z",
#                             "localId"=>nil,
#                             "mediaId"=>20,
#                             "mediaType"=>"image",
#                             "position"=>1,
#                             "publicId"=>"dfhjghjkdisudgfds7iy18"},
#                            {"createdAt"=>"2015-09-28T15:04:02.055Z",
#                             "localId"=>nil,
#                             "mediaId"=>19,
#                             "mediaType"=>"image",
#                             "position"=>0,
#                             "publicId"=>"dfhjghjkdisudgfds7iy17"}],
#                       "notes"=>[],
#                       "reslotsCounter"=>0,
#                       "settings"=>{"alerts"=>"0000000000"},
#                       "shareUrl"=>nil,
#                       "startDate"=>"2019-09-24T23:44:02.000Z",
#                       "title"=>"Slot title 23",
#                       "updatedAt"=>"2015-09-28T15:04:02.051Z",
#                       "visibility"=>"public"},
#                  "target"=>nil,
#                  "time"=>"2015-09-28T15:04:02.000000",
#                  "to"=>["aggregated:65", "notification:65"],
#                  "user"=>
#                      {"createdAt"=>"2015-09-25T21:22:16.257Z",
#                       "deletedAt"=>nil,
#                       "friendsCount"=>0,
#                       "id"=>53,
#                       "image"=>{"localId"=>nil, "publicId"=>nil},
#                       "reslotCount"=>0,
#                       "slotCount"=>5,
#                       "updatedAt"=>"2015-09-25T21:22:16.257Z",
#                       "username"=>"User 53"},
#
#                  "verb"=>"comment"}],
#            "activity_count"=>1,
#            "actor_count"=>1,
#            "created_at"=>"2015-09-28T15:04:02.000000",
#            "group"=>"11357_2015-09-28",
#            "id"=>"27451d00-65f2-11e5-8dee-0a23828fb133",
#            "is_read"=>false,
#            "is_seen"=>true,
#            "updated_at"=>"2015-09-28T15:04:02.000000",
#            "verb"=>"comment"}]
#      )
#   end
# end
