---
development:
  cloud_name: <%= ENV['TS_RAILS_BACKEND_CLOUDINARY_CLOUD_NAME'] %>
  api_key: <%= ENV['TS_RAILS_BACKEND_CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['TS_RAILS_BACKEND_CLOUDINARY_API_SECRET'] %>
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: <%= ENV['TS_RAILS_BACKEND_CLOUDINARY_CLOUD_NAME'] %>
  api_key: <%= ENV['TS_RAILS_BACKEND_CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['TS_RAILS_BACKEND_CLOUDINARY_API_SECRET'] %>
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: <%= ENV['TS_RAILS_BACKEND_CLOUDINARY_CLOUD_NAME'] %>
  api_key: <%= ENV['TS_RAILS_BACKEND_CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['TS_RAILS_BACKEND_CLOUDINARY_API_SECRET'] %>
  enhance_image_tag: true
  static_image_support: false
