# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause this
# file to always be loaded, without a need to explicitly require it in any files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, make a
# separate helper file that requires this one and then use it only in the specs
# that actually need it.
#
# The `.rspec` file also contains a few flags that are not defaults but that
# users commonly want.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  # The settings below are suggested to provide a good initial experience
  # with RSpec, but feel free to customize to your heart's content.
  # These two settings work together to allow you to limit a spec run
  # to individual examples or groups you care about by tagging them with
  # `:focus` metadata. When nothing is tagged with `:focus`, all examples
  # get run.
  config.filter_run :focus, :db, :explain
  config.run_all_when_everything_filtered = true

  # Many RSpec users commonly either run the entire suite or an individual
  # file, and it's useful to allow more verbose output when running an
  # individual spec file.
  if config.files_to_run.one?
    # Use the documentation formatter for detailed output,
    # unless a formatter has already been configured
    # (e.g. via a command-line flag).
    config.default_formatter = 'doc'
  end

  # Print the 10 slowest examples and example groups at the
  # end of the spec run, to help surface which specs are running
  # particularly slow.
  config.profile_examples = 2

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = :random

  # Seed global randomization in this process using the `--seed` CLI option.
  # Setting this allows you to use `--seed` to deterministically reproduce
  # test failures related to randomization by passing the same `--seed` value
  # as the one that triggered the failure.
  Kernel.srand config.seed

  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library such as wrong or the stdlib/minitest
  # assertions if you prefer.
  config.expect_with :rspec do |expectations|
    # Enable only the newer, non-monkey-patching expect syntax.
    # For more details, see:
    #   - http://myronmars.to/n/dev-blog/2012/06/rspecs-new-expectation-syntax
    expectations.syntax = :expect
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or mocha) by changing the `mock_with` option here.
  config.mock_with :rspec do |mocks|
    # Enable only the newer, non-monkey-patching expect syntax.
    # For more details, see:
    #   - http://teaisaweso.me/blog/2013/05/27/rspecs-new-message-expectation-syntax/
    mocks.syntax = :expect

    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended.
    mocks.verify_partial_doubles = true
  end

  config.include(FactoryGirl::Syntax::Methods,
                 type: :services,
                 file_path: %r{/spec\/services/}
                )

  if defined?(Bullet) && Bullet.enable?
    config.before(:each) do
      Bullet.start_request
    end

    config.after(:each) do
      Bullet.perform_out_of_channel_notifications if Bullet.notification?
      Bullet.end_request
    end
  end

  config.around(:each, :db) do |example|
    with_std_out_logger { example.run }
  end

  config.before(:all, :seed) do
    Rails.application.load_seed
    # load "#{Rails.root}/db/seeds.rb"
  end

  config.before(:each, :aws) do
    allow(Device).to receive(:create_client).and_return(Aws::SNS::Client.new(stub_responses: true))
  end

  config.before(:each, :async) do
    require 'sucker_punch/testing/inline'
  end

  config.before(:each, :explain) do
    ActiveRecord::ConnectionAdapters::PostgreSQLAdapter.show_explain
  end

  config.after(:each, :explain) do
    ActiveRecord::ConnectionAdapters::PostgreSQLAdapter.hide_explain
  end

  # Disable triggering activities through callbacks (can re-activated with flag :activity)
  #
  # http://api.rubyonrails.org/classes/ActiveSupport/Callbacks/ClassMethods.html
  # http://stackoverflow.com/questions/516579/is-there-a-way-to-get-a-collection-of-all-the-models-in-your-rails-app
  # http://stackoverflow.com/questions/3303347/given-a-class-see-if-instance-has-method-ruby

  config.before(:suite) do
    ActiveRecord::Base.descendants.each do |model| # ActiveRecord::Base.subclasses.map(&:name)
      # Disable triggering activities through callbacks
      if model.include?(Activity)
        model.skip_callback(:commit, :after, :create_activity)
      end
    end
  end

  config.before(:each, :activity) do
    # Enable triggering activities through callbacks
    ActiveRecord::Base.descendants.each do |model|
      if model.include?(Activity)
        model.set_callback(:commit, :after, :create_activity, on: :create)
      end
    end
  end

  config.after(:each, :activity) do
    # Disable triggering activities through callbacks (after it was enabled)
    ActiveRecord::Base.descendants.each do |model|
      if model.include?(Activity)
        model.skip_callback(:commit, :after, :create_activity)
      end
    end
  end
end

def with_std_out_logger
  default_logger = ActiveRecord::Base.logger
  ActiveRecord::Base.logger = Logger.new(STDOUT)
  yield
ensure
  ActiveRecord::Base.logger = default_logger
end
